name: zego_pip
description: "A Flutter Picture-in-Picture (PIP) plugin based on `zego_express_engine`, supporting iOS and Android platforms ."
version: 0.0.1
homepage: https://www.zegocloud.com/
repository: https://github.com/ZEGOCLOUD/zego_pip_flutter
screenshots:
  - description: "Android Picture-in-Picture demo showing video playback in floating window"
    path: images/android.gif
  - description: "iOS Picture-in-Picture demo showing video playback in floating window"
    path: images/ios.gif

environment:
  sdk: ^3.8.1
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  floating: ^6.0.0
  zego_express_engine: ^3.21.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  dartdoc: ^8.3.3

flutter:
  plugin:
    platforms:
      android:
        package: im.zego.pip.zego_pip
        pluginClass: ZegoPipPlugin
      ios:
        pluginClass: ZegoPipPlugin


topics:
  - pip
  - zego_express_engine